#声明电影微服务的端口号
server:
  port: 8001
  
#配置电影微服务
spring:
  #定义电影微服务的名称
  application:
    name: microservice-movie

#向eureka服务器注册
eureka:
  #注册前
  client:
    #向eureka服务器注册自己
    register-with-eureka: true
    #向Eureka服务器
    fetch-registry: true
    #微服务的消费方与eureka服务器的约定
    #每隔30秒获取并刷新注册信息,默认是30秒
    registry-fetch-interval-seconds: 30
    #注册到url指定的eureka服务器上
    service-url:
      defaultZone: http://192.168.41.1:8888/eureka
    
   

    
